volumes:
    postgres_data:
        driver: local
    redis_data:
        driver: local
    electric_data:
        driver: local

services:
    postgres:
        # you can connect with e.g.
        # psql -h localhost -p 5556 -U postgres -d db
        image: postgres:17
        command: >
            postgres
            -c wal_level=logical
            -c max_replication_slots=10
            -c max_wal_senders=10
            -c shared_preload_libraries=pg_stat_statements
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5556:5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5